export default {
  title: 'light',
  colors: {
    primary: '#15C3D6',
    secondary: '#FFD666',
    terciary: '#FF669D',
    fouth: '#37C77F',
    background: '#F5F8FA',
    backgroundInput: '#F5F8FA',
    text: '#8FA7B2',
    backgroundEffectTop: '#29b6d1',
    backgroundEffectBotton: '#00c7c7',
    hoverButton: '#96feff',
    backgroundForm: '#ffffff',
    border: '#d3e2e5',
    borderLeaflet: '#03e2e5',
    legend: '#5c8599',
    backgroundButtonActive: '#edfff6',
    borderButtonActive: '#a1e9c5',
    colorButtonActive: '#37c77f',
    confirmButton: '#3cdc8c',
  },
};
